### PR TITLE
Helm chart: ADOT-EKS-on-EC2-to-CW

### PR DESCRIPTION
**Pull request by hyunuk**
This PR is to add our Helm chart to adot-eks-on-ec2-to-cw folder in aws-otel-community repository, to deploy Fluent Bit and ADOT Collector as DaemonSets to EKS on EC2 to collect logs and metrics and send them to Amazon CloudWatch for storage and analytics.

Contributors:
@hyunuk 
@JamesJHPark 

CC:
@alolita

### CODE REVIEW

**Review by anuraaga — COMMENTED** [review]
Is there any document summarizing the high level of this helm chart / project? I don't think aws-otel-community is an appropriate repository for a helm chart.

I'm also wondering
- Is this actually tied to EC2?
- Instead of the concept of CW being in the helm chart name, it should just be a configuration open in a generic `adot-eks-addon` I think

/cc @alolita

**Comment by alolita** [comment]
@anuraaga This Helm chart will be used by the community for an easy way to setup metrics and logs collection from self-managed EKS on EC2 clusters to send to CWCI. This Helm chart uses ADOT for collecting metrics and FluentBit for collecting logs. This Helm chart is not used for EKS add-ons or bundled in ADOT. 

I expect different types of "convenience Helm charts" to be added to this charts repo for the community to use and contribute to hence the location in the community repo. As a precedence, the Prometheus project also maintains a similar setup - see https://github.com/prometheus-community/helm-charts.

**Review by alolita — APPROVED** [review]

**Comment by anuraaga** [comment]
@alolita The main issue is that this repo isn't specific to helm charts. Helm charts or operators require a sort of maintainance (code review, tests, etc) that are quite different from other things and we wouldn't expect to mangle them into a broad repo like this one, which I thought is generally supposed to be for community discussions and not code. The prometheus community example looks fine since it has a repo for helm-charts.

I'm not too sure if there is anything really different here vs some of the other repos like aws-otel-js, they are repos providing ways to incorporate ADOT into user systems. So it seems we would want an `aws-observability/aws-otel-operator` which would be the entry point into incorporating ADOT into user k8s sites.

**Comment by anuraaga** [comment]
A concrete problem is that now we have a folder with a CONTRIBUTING.md, LICENSE, etc - this is not how we are supposed to be structuring our repos

**Comment by anuraaga** [comment]
@hyunuk I created a repo aws-otel-helm-charts

https://github.com/aws-observability/aws-otel-helm-charts

It has some content that we don't need anymore. Do you mind removing the content in that repo and moving in this chart? Please make sure to put the Contributing.md, etc at the top level, not in a subfolder. Thanks

**Pull request merged**
